[package]
name = "solitare"
version = "0.1.0"
edition = "2021"
authors = ["John Ellis"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
arr_macro = "0.2.1"
